[build]
  base = "."
  command = "cd apps/frontend && npm install && npm run build"
  publish = "apps/frontend/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  # Используем настройки npm/lock-файл по умолчанию

