[build]
  base = "apps/frontend"
  command = "npm install && npm run build"
  publish = "apps/frontend/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

