[phases.setup]
nixPkgs = ["python311", "poetry"]

[phases.install]
cmds = ["poetry install --no-dev"]

[phases.build]
cmds = []

[start]
cmd = "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT"

